const SupportTicket = require('../models/SupportTicket');
const Notification = require('../models/Notification');
const { asyncHandler, ApiError } = require('../middleware/errorHandler');
const { generateId } = require('../utils/helpers');

const getUserId = (req) => req.user.id || req.user.sub;

const FAQS = [
  {
    category: 'Bookings',
    question: 'How do I book an appointment with a doctor?',
    answer: 'Search for your preferred doctor or specialty on the home screen, select a suitable time slot, enter patient details, and confirm the booking.',
  },
  {
    category: 'Bookings',
    question: 'Can I cancel or reschedule my appointment?',
    answer: 'Yes, go to My Appointments, select the booking, and tap Cancel. Rescheduling is available up to 2 hours before the slot time.',
  },
  {
    category: 'Payments',
    question: 'What payment methods are supported?',
    answer: 'We support eSewa, Khalti, bank cards, and pay-at-clinic for walk-in and physical consultations.',
  },
  {
    category: 'Video Consult',
    question: 'How do video consultations work?',
    answer: 'At your appointment time, open the app and tap "Join Call" on your appointment card. Ensure camera and microphone permissions are granted.',
  },
  {
    category: 'Lab Tests',
    question: 'How do home sample collections work?',
    answer: 'After booking a lab test with home collection, a qualified phlebotomist will visit your specified address at your selected time window.',
  },
  {
    category: 'Prescriptions',
    question: 'Where can I find my digital prescriptions?',
    answer: 'All prescriptions generated by your doctor are securely saved under the "Prescriptions" tab on your health dashboard.',
  },
];

/**
 * Get FAQs
 */
const getFaqs = asyncHandler(async (req, res) => {
  res.json(FAQS);
});

/**
 * Create a support ticket
 */
const createTicket = asyncHandler(async (req, res) => {
  const userId = getUserId(req);
  const { subject, message, category } = req.body;
  if (!subject || !message) {
    throw new ApiError(400, 'Subject and message are required');
  }

  const ticketId = generateId('tkt');
  const now = new Date().toISOString();

  const ticket = await SupportTicket.create({
    id: ticketId,
    user_id: userId,
    subject,
    message,
    category: category || 'General',
    status: 'open',
    reply: null,
    created_at: now,
  });

  try {
    await Notification.create({
      id: generateId('notif'),
      user_id: userId,
      title: 'Support ticket received',
      message: `We received your ticket "${subject}". We'll respond within 24 hours.`,
      type: 'system',
      read: false,
      created_at: now,
    });
  } catch (err) {}

  const ticketObj = ticket.toObject();
  delete ticketObj._id;
  delete ticketObj.__v;

  res.json(ticketObj);
});

/**
 * Get user's support tickets
 */
const getTickets = asyncHandler(async (req, res) => {
  const userId = getUserId(req);
  let items = await SupportTicket.find({ user_id: userId })
    .sort({ created_at: -1 })
    .limit(100)
    .lean();

  items = items.map(t => {
    const obj = { ...t };
    delete obj._id;
    delete obj.__v;
    return obj;
  });

  res.json(items);
});

module.exports = {
  getFaqs,
  createTicket,
  getTickets,
};
